# Generated by Django 4.1.2 on 2022-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_ida', models.CharField(max_length=200)),
                ('fecha_vuelta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_vuelo', models.CharField(max_length=200)),
                ('hora_vuelo', models.CharField(max_length=200)),
            ],
        ),
    ]
