# Generated by Django 4.1.2 on 2022-10-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_paquete_vuelos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelos',
            old_name='nombre',
            new_name='destino',
        ),
        migrations.RemoveField(
            model_name='vuelos',
            name='hora_vuelo',
        ),
    ]
