# Generated by Django 4.1.2 on 2022-11-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_delete_paquete_delete_vuelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creado_el',
            field=models.DateField(auto_created=True, default=None),
        ),
        migrations.AddField(
            model_name='reserva',
            name='destino_reserva',
            field=models.CharField(choices=[('Hotel Ibis Bogota Museo, 6 noches + aereo', 'Bogota'), ('Hotel CCT Caracas, 6 noches + aereo', 'Caracas'), ('Hotel Vila Santa Teresa Río de Janeiro, 6 noches + aereo', 'Rio De Janeiro'), ('Hotel FAUNA Montevideo, 6 noches + aereo', 'Montevideo'), ('Hotel Huinid Pioneros San Carlos de Bariloche, 6 noches + aereo', 'Bariloche'), ('Hotel Alma Pura Puerto Iguazú, 6 noches + aereo', 'Iguazu'), ('Hotel Raices Aconcagua Mendoza, 6 noches + aereo', 'Mendoza')], default='Hotel Ibis Bogota Museo, 6 noches + aereo', max_length=100),
        ),
    ]
