# Generated by Django 4.1.2 on 2022-11-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_reserva_creado_el_reserva_destino_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='creado_el',
            field=models.DateField(auto_now=True),
        ),
    ]
