# Generated by Django 4.1.2 on 2022-11-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_alter_reserva_creado_el'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='creado_el',
        ),
    ]
