# Generated by Django 4.1.2 on 2022-11-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0010_remove_reserva_creado_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='destino_reserva',
            field=models.CharField(choices=[('Hotel Ibis Bogota Museo, 6 noches + aereo', 'Ibis Bogota'), ('Hotel CCT Caracas, 6 noches + aereo', 'Cct Caracas'), ('Hotel Vila Santa Teresa Río de Janeiro, 6 noches + aereo', 'Vila Santa Teresa Rio De Janeiro'), ('Hotel FAUNA Montevideo, 6 noches + aereo', 'Fauna Montevideo'), ('Hotel Huinid Pioneros San Carlos de Bariloche, 6 noches + aereo', 'Huinid Pioneros Bariloche'), ('Hotel Alma Pura Puerto Iguazú, 6 noches + aereo', 'Alma Pura Iguazu'), ('Hotel Raices Aconcagua Mendoza, 6 noches + aereo', 'Raices Aconcagua Mendoza')], default='Hotel Ibis Bogota Museo, 6 noches + aereo', max_length=100),
        ),
    ]
