# Generated by Django 4.1.2 on 2022-11-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_ida', models.CharField(max_length=200)),
                ('fecha_vuelta', models.CharField(max_length=200)),
            ],
        ),
    ]
