# Generated by Django 4.1.2 on 2022-11-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelos',
            name='fecha_vuelo',
        ),
        migrations.AddField(
            model_name='vuelos',
            name='fecha_vuelo_ida',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vuelos',
            name='fecha_vuelo_vuelta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='destino',
            field=models.CharField(choices=[('1', 'Bogotá'), ('2', 'Caracas'), ('3', 'Río de Janeiro'), ('4', 'Montevideo'), ('5', 'San Carlos de Bariloche'), ('6', 'Puerto Iguazú'), ('7', 'Mendoza')], default='5', max_length=100),
        ),
    ]
