# Generated by Django 4.1.2 on 2022-11-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_remove_vuelos_fecha_vuelo_vuelos_fecha_vuelo_ida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='destino',
            field=models.CharField(choices=[('Bogotá', 'Colombia'), ('Caracas', 'Venezuela'), ('Río de Janeiro', 'Brazil'), ('Montevideo', 'Uruguay'), ('San Carlos de Bariloche', 'Argentina1'), ('Puerto Iguazú', 'Argentina2'), ('Mendoza', 'Argentina3')], default='San Carlos de Bariloche', max_length=100),
        ),
    ]
