# Generated by Django 4.1.2 on 2022-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_alter_vuelos_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='destino',
            field=models.CharField(choices=[('Bogotá', 'Bogota'), ('Caracas', 'Caracas'), ('Río de Janeiro', 'Rio De Janeiro'), ('Montevideo', 'Montevideo'), ('San Carlos de Bariloche', 'Bariloche'), ('Puerto Iguazú', 'Iguazu'), ('Mendoza', 'Mendoza')], default='Bogotá', max_length=100),
        ),
    ]
