# Generated by Django 4.1.2 on 2022-11-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0005_vuelos_nombre_vuelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelos',
            old_name='nombre_vuelo',
            new_name='nombre_pasajero',
        ),
    ]
