# Generated by Django 4.1.2 on 2022-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0006_rename_nombre_vuelo_vuelos_nombre_pasajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='fecha_vuelo_ida',
            field=models.CharField(default='', max_length=100),
        ),
    ]
