# Generated by Django 4.1.2 on 2022-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_opiniones', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('breve_opinion', models.CharField(default='', max_length=300)),
                ('opinion_detallada', models.CharField(default='', max_length=3000)),
                ('firma', models.CharField(default='', max_length=30)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='opiniones')),
            ],
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
